# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run a one-line script
        run: echo Hello, world!

      - name: rr
        run: |
            echo "will =============build============"
            npm run build
            echo "will =============--clean============"
            npm test --clean
            echo "will ===========lint=============="
            npm run lint
      - name: rr2
        run: |
            echo "will =============tree============"
            tree